=== NeoRaysGitHub/NeoRaysTraining/Xml/XSDExamples/books.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://booksinfo.com"
	elementFormDefault="qualified">
	<element name="books">
		<complexType>
			<sequence>
				<element name="book" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="author" type="string" minOccurs="1" maxOccurs="unbounded" />
							<element name="publication" type="string" />
						</sequence>
						<attribute name="isbn" type="string"  />
						<attribute name="title" type="string" />
						<attribute name="price" type="double" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== NeoRaysGitHub/NeoRaysTraining/Xml/XSDExamples/books.xml
<books xmlns="http://booksinfo.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://booksinfo.com D://XML/books.xsd">
	<book isbn="Neorays" title="XML" price="100">
		<author>Suresh</author>
		<publication>Neorays</publication>
	</book>
	<book isbn="Neorays">
	  <author>Hari</author>
	  <author>Mittu</author>
	  <publication>Neo</publication>
	</book>
</books>
